[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd ~/academia/"
desc = "goto academia"

[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "goto root"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd /tmp"
desc = "goto tmp"

[[mgr.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd ~/Videos"
desc = "goto Videos"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "goto Pictures"
